CREATE TABLE RIGHTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE ROLES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE ROLE_RIGHT (
    role_id INT REFERENCES ROLES(id),
    right_id INT REFERENCES RIGHTS(id),
    PRIMARY KEY (role_id, right_id)
);

CREATE TABLE SUBSCRIPTIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    type VARCHAR(50),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50),
    email VARCHAR(200) UNIQUE,
    password VARCHAR(255),
    profile_photo_path VARCHAR(255),
    state INT,
    last_activity DATETIME,
    visibility INT,
    street VARCHAR(100),
    city VARCHAR(50),
    country VARCHAR(50),
    description VARCHAR(255),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    role_id INT NOT NULL DEFAULT 1 REFERENCES ROLES(id) ON DELETE CASCADE,
    subscription_id INT NOT NULL DEFAULT 1 REFERENCES SUBSCRIPTIONS(id) ON DELETE CASCADE,
    subscription_updated_at INT CHECK(subscription_updated_at>=0),
    email_verified_at VARCHAR(255),
    email_verification_token VARCHAR(255),
    email_verification_expiration INT CHECK(email_verification_expiration>=0),
    status VARCHAR(15)
    banned_until INT NULL,
    ban_start DATETIME NULL,
    ban_duration INT NULL,
    ban_reason VARCHAR(255) NULL
);

CREATE TABLE TALKS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    type VARCHAR(50),
    description VARCHAR(255),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE EVENTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100),
    description VARCHAR(255),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    talk_id INT UNIQUE NOT NULL REFERENCES TALKS(id) ON DELETE CASCADE
);

CREATE TABLE MESSAGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT,
    path VARCHAR(255),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    user_id INT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    talk_id INT NOT NULL REFERENCES TALKS(id) ON DELETE CASCADE,
    message_id INT NULL REFERENCES MESSAGES(id) ON DELETE CASCADE
);

CREATE TABLE MESSAGE_LIKES (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    message_id INT REFERENCES MESSAGES(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, message_id)
);

CREATE TABLE REACTIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    emoji TEXT,
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE USER_MESSAGE_REACTION (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    message_id INT REFERENCES MESSAGES(id) ON DELETE CASCADE,
    reaction_id INT REFERENCES REACTIONS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, message_id, reaction_id)
);

CREATE TABLE FRIENDS (
    sender_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    receiver_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    state INT,
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    PRIMARY KEY (sender_user_id, receiver_user_id)
);

CREATE TABLE FOLLOWERS (
    sender_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    receiver_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    state INT,
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    PRIMARY KEY (sender_user_id, receiver_user_id)
);

CREATE TABLE EXCHANGES (
    id INT AUTO_INCREMENT,
    sender_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    receiver_user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    content TEXT,
    file_path VARCHAR(250),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    PRIMARY KEY (id, sender_user_id, receiver_user_id)
);

CREATE TABLE USER_EXCHANGE_REACTION (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    exchange_id INT REFERENCES EXCHANGES(id) ON DELETE CASCADE,
    reaction_id INT REFERENCES REACTIONS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, exchange_id, reaction_id)
);

CREATE TABLE USER_TALK (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    talk_id INT REFERENCES TALKS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, talk_id)
);

CREATE TABLE USER_EVENT (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    event_id INT REFERENCES EVENTS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, event_id)
);

CREATE TABLE MOODS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20),
    color VARCHAR(10),
    text_color VARCHAR(10),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE USER_MOOD (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    mood_id INT REFERENCES MOODS(id) ON DELETE CASCADE,
    attached_at DATETIME DEFAULT NOW(),
    PRIMARY KEY (user_id, mood_id, attached_at)
);

CREATE TABLE EVENT_LIKES (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    event_id INT REFERENCES EVENTS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, event_id)
);

CREATE TABLE CAPTCHAS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50),
    content VARCHAR(50),
    question VARCHAR(200),
    answer VARCHAR(200),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    user_id INT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(4),
    ip VARCHAR(45),
    requested_at DATETIME DEFAULT NOW(),
    user_id INT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    script_name VARCHAR(255),
    http_referer VARCHAR(255),
    request_uri VARCHAR(255),
    request_method VARCHAR(255),
    server_protocol VARCHAR(255),
    http_user_agent VARCHAR(255)
);

CREATE TABLE NEWSLETTERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    object VARCHAR(255),
    content TEXT,
    created_at DATETIME DEFAULT NOW(),
    user_id INT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE
);

CREATE TABLE CUSTOMS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image VARCHAR(255),
    category VARCHAR(50),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    user_id INT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE
);


CREATE TABLE USER_CUSTOM (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    custom_id INT REFERENCES CUSTOMS(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, custom_id)
);

CREATE TABLE USER_BADGE (
    user_id INT REFERENCES USERS(id) ON DELETE CASCADE,
    badge_id INT REFERENCES BAGDES(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, badge_id),
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW()
);

CREATE TABLE BADGES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    badge TEXT,
    updated_at DATETIME DEFAULT NOW() ON UPDATE NOW(),
    created_at DATETIME DEFAULT NOW(),
    user_id INT NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    mood_id INT NOT NULL REFERENCES MOODS(id) ON DELETE CASCADE
);
